export const SET_LOADING = "SET_LOADING"

export const GET_PLAYING_CURRENTLY_SUCCESS = "GET_PLAYING_CURRENTLY_SUCCESS"
export const GET_PLAYING_CURRENTLY_FAILURE = "GET_PLAYING_CURRENTLY_FAILURE"

export const RESUME_PLAY_SUCCESS = "RESUME_PLAY_SUCCESS"
export const RESUME_PLAY_FAILURE = "RESUME_PLAY_FAILURE"

export const PAUSE_CURRENT_TRACK_SUCCESS = "PAUSE_CURRENT_TRACK_SUCCESS"
export const PAUSE_CURRENT_TRACK_FAILURE = "PAUSE_CURRENT_TRACK_FAILURE"

